export const CATEGORIES = [
  { value: "Information Technology", icon: "💻" },
  { value: "Business & Management", icon: "📊" },
  { value: "Accounting & Finance", icon: "💰" },
  { value: "Marketing & Sales", icon: "📈" },
  { value: "Design & Creative Arts", icon: "🎨" },
  { value: "Media & Communication", icon: "🎬" },
  { value: "Healthcare & Nursing", icon: "🏥" },
  { value: "Education & Teaching", icon: "🧑‍🏫" },
  { value: "Law & Legal Studies", icon: "⚖️" },
  { value: "Engineering", icon: "🏗️" },
  { value: "Science", icon: "🔬" },
  { value: "Social Sciences", icon: "🌍" },
  { value: "Hospitality & Tourism", icon: "🏨" },
  { value: "Technical & Vocational", icon: "🛠️" },
  { value: "Agriculture & Environment", icon: "🚜" },
  { value: "Psychology & Counseling", icon: "🧠" },
  { value: "Languages & Literature", icon: "🌐" },
  { value: "Sports & Physical Education", icon: "🏃" },
  { value: "Aviation & Logistics", icon: "✈️" },
  { value: "Cybersecurity", icon: "🔐" },
];
