import "dotenv/config";
import mongoose from "mongoose";
import dns from "node:dns";
import Career from "../models/Career.js";

dns.setDefaultResultOrder("ipv4first");

const careers = [
  {
    title: "Software Engineer",
    slug: "software-engineer",
    description: "Design, develop, and maintain software applications. Work with teams to build scalable web, mobile, and enterprise solutions using modern programming languages and frameworks.",
    streamTags: ["Maths", "Tech"],
    salaryMinLKR: 80000,
    salaryMaxLKR: 350000,
    demandLevel: "High",
    requiredSkills: ["JavaScript", "Python", "Problem Solving", "Data Structures", "Git"],
    educationPaths: ["BSc Computer Science", "BSc Software Engineering", "Diploma in IT"],
    workEnvironment: "Office / Remote",
    imageUrl: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400&h=250&fit=crop",
  },
  {
    title: "Data Scientist",
    slug: "data-scientist",
    description: "Analyse large datasets to extract meaningful insights using statistical methods, machine learning, and data visualisation techniques to drive business decisions.",
    streamTags: ["Maths", "Tech"],
    salaryMinLKR: 100000,
    salaryMaxLKR: 400000,
    demandLevel: "High",
    requiredSkills: ["Python", "Machine Learning", "Statistics", "SQL", "Data Visualization"],
    educationPaths: ["BSc Data Science", "BSc Statistics", "MSc Computer Science"],
    workEnvironment: "Office / Remote",
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop",
  },
  {
    title: "Doctor (MBBS)",
    slug: "doctor-mbbs",
    description: "Diagnose and treat illnesses, prescribe medications, and advise patients on health matters. Work in hospitals, clinics, and community health settings across Sri Lanka.",
    streamTags: ["Bio"],
    salaryMinLKR: 90000,
    salaryMaxLKR: 500000,
    demandLevel: "High",
    requiredSkills: ["Biology", "Chemistry", "Communication", "Critical Thinking", "Empathy"],
    educationPaths: ["MBBS", "MD Specialization"],
    workEnvironment: "Hospital / Clinic",
    imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=250&fit=crop",
  },
  {
    title: "Chartered Accountant",
    slug: "chartered-accountant",
    description: "Provide financial advice, audit accounts, and ensure compliance with financial regulations. Help organisations with tax planning, budgeting, and financial reporting.",
    streamTags: ["Commerce", "Maths"],
    salaryMinLKR: 75000,
    salaryMaxLKR: 450000,
    demandLevel: "High",
    requiredSkills: ["Accounting", "Financial Analysis", "Auditing", "Tax Planning", "Attention to Detail"],
    educationPaths: ["CA Sri Lanka", "BSc Accounting", "ACCA"],
    workEnvironment: "Office",
    imageUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=250&fit=crop",
  },
  {
    title: "Civil Engineer",
    slug: "civil-engineer",
    description: "Plan, design, and oversee construction of infrastructure projects including roads, bridges, buildings, and water systems that shape the built environment.",
    streamTags: ["Maths", "Tech"],
    salaryMinLKR: 70000,
    salaryMaxLKR: 300000,
    demandLevel: "Medium",
    requiredSkills: ["AutoCAD", "Structural Analysis", "Project Management", "Mathematics", "Problem Solving"],
    educationPaths: ["BSc Civil Engineering", "NDT Civil Engineering"],
    workEnvironment: "Office / Field",
    imageUrl: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=400&h=250&fit=crop",
  },
  {
    title: "Graphic Designer",
    slug: "graphic-designer",
    description: "Create visual content for digital and print media including logos, websites, advertisements, and brand identities using design software and creative thinking.",
    streamTags: ["Arts", "Tech"],
    salaryMinLKR: 45000,
    salaryMaxLKR: 200000,
    demandLevel: "Medium",
    requiredSkills: ["Adobe Photoshop", "Illustrator", "UI/UX", "Typography", "Creativity"],
    educationPaths: ["BSc Design", "Diploma in Graphic Design", "HND Multimedia"],
    workEnvironment: "Office / Freelance / Remote",
    imageUrl: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400&h=250&fit=crop",
  },
  {
    title: "Pharmacist",
    slug: "pharmacist",
    description: "Dispense medications, counsel patients on drug use, and collaborate with healthcare professionals to ensure safe and effective pharmaceutical care.",
    streamTags: ["Bio"],
    salaryMinLKR: 60000,
    salaryMaxLKR: 250000,
    demandLevel: "Medium",
    requiredSkills: ["Pharmacology", "Chemistry", "Patient Care", "Attention to Detail", "Communication"],
    educationPaths: ["BPharm", "MPharm"],
    workEnvironment: "Pharmacy / Hospital",
    imageUrl: "https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400&h=250&fit=crop",
  },
  {
    title: "Digital Marketing Specialist",
    slug: "digital-marketing-specialist",
    description: "Plan and execute digital marketing campaigns across social media, SEO, email, and paid advertising to grow brand awareness and drive business results.",
    streamTags: ["Commerce", "Arts", "Tech"],
    salaryMinLKR: 50000,
    salaryMaxLKR: 250000,
    demandLevel: "High",
    requiredSkills: ["SEO", "Social Media Marketing", "Google Analytics", "Content Strategy", "Copywriting"],
    educationPaths: ["BSc Marketing", "Diploma in Digital Marketing", "BBA"],
    workEnvironment: "Office / Remote",
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=250&fit=crop",
  },
  {
    title: "Mechanical Engineer",
    slug: "mechanical-engineer",
    description: "Design, analyse, and manufacture mechanical systems ranging from engines and HVAC to robotics and manufacturing equipment.",
    streamTags: ["Maths", "Tech"],
    salaryMinLKR: 65000,
    salaryMaxLKR: 280000,
    demandLevel: "Medium",
    requiredSkills: ["SolidWorks", "Thermodynamics", "Material Science", "CAD", "Problem Solving"],
    educationPaths: ["BSc Mechanical Engineering", "NDT Mechanical Engineering"],
    workEnvironment: "Factory / Office / Field",
    imageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&h=250&fit=crop",
  },
  {
    title: "Lawyer",
    slug: "lawyer",
    description: "Represent clients in legal proceedings, draft legal documents, provide legal counsel, and advocate for rights in courts and tribunals across Sri Lanka.",
    streamTags: ["Arts", "Commerce"],
    salaryMinLKR: 60000,
    salaryMaxLKR: 400000,
    demandLevel: "Medium",
    requiredSkills: ["Legal Research", "Critical Thinking", "Communication", "Negotiation", "Writing"],
    educationPaths: ["LLB", "Attorney-at-Law (SLITHM)", "LLM"],
    workEnvironment: "Court / Office",
    imageUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400&h=250&fit=crop",
  },
  {
    title: "UX/UI Designer",
    slug: "ux-ui-designer",
    description: "Research user needs and design intuitive interfaces for web and mobile applications, creating wireframes, prototypes, and visual designs that delight users.",
    streamTags: ["Tech", "Arts"],
    salaryMinLKR: 70000,
    salaryMaxLKR: 300000,
    demandLevel: "High",
    requiredSkills: ["Figma", "User Research", "Wireframing", "Prototyping", "Visual Design"],
    educationPaths: ["BSc IT", "BSc Design", "Diploma in UX Design"],
    workEnvironment: "Office / Remote",
    imageUrl: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=400&h=250&fit=crop",
  },
  {
    title: "Biomedical Scientist",
    slug: "biomedical-scientist",
    description: "Conduct laboratory research and diagnostic testing to understand diseases, develop treatments, and advance medical knowledge through scientific investigation.",
    streamTags: ["Bio", "Maths"],
    salaryMinLKR: 65000,
    salaryMaxLKR: 250000,
    demandLevel: "Medium",
    requiredSkills: ["Lab Techniques", "Molecular Biology", "Data Analysis", "Research Methods", "Biochemistry"],
    educationPaths: ["BSc Biomedical Science", "BSc Biology", "MSc Biotechnology"],
    workEnvironment: "Laboratory / Hospital",
    imageUrl: "https://images.unsplash.com/photo-1579154204601-01588f351e67?w=400&h=250&fit=crop",
  },
  {
    title: "Banking & Finance Manager",
    slug: "banking-finance-manager",
    description: "Oversee banking operations, manage financial portfolios, assess risks, and lead teams to deliver financial services and investment strategies to clients.",
    streamTags: ["Commerce", "Maths"],
    salaryMinLKR: 85000,
    salaryMaxLKR: 400000,
    demandLevel: "High",
    requiredSkills: ["Financial Analysis", "Risk Management", "Leadership", "Banking Operations", "Excel"],
    educationPaths: ["BBA", "BSc Finance", "MBA", "CIMA"],
    workEnvironment: "Office",
    imageUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=250&fit=crop",
  },
  {
    title: "Architect",
    slug: "architect",
    description: "Design buildings and spaces that are functional, safe, and aesthetically pleasing while considering environmental sustainability and cultural context.",
    streamTags: ["Maths", "Arts"],
    salaryMinLKR: 70000,
    salaryMaxLKR: 350000,
    demandLevel: "Medium",
    requiredSkills: ["AutoCAD", "SketchUp", "3D Modelling", "Creativity", "Spatial Awareness"],
    educationPaths: ["BSc Architecture", "MSc Architecture"],
    workEnvironment: "Office / Field",
    imageUrl: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=400&h=250&fit=crop",
  },
  {
    title: "Cybersecurity Analyst",
    slug: "cybersecurity-analyst",
    description: "Protect organisations from cyber threats by monitoring networks, identifying vulnerabilities, implementing security measures, and responding to security incidents.",
    streamTags: ["Tech", "Maths"],
    salaryMinLKR: 90000,
    salaryMaxLKR: 380000,
    demandLevel: "High",
    requiredSkills: ["Network Security", "Ethical Hacking", "SIEM Tools", "Linux", "Risk Assessment"],
    educationPaths: ["BSc Cybersecurity", "BSc IT", "CEH Certification", "CompTIA Security+"],
    workEnvironment: "Office / Remote",
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop",
  },
  {
    title: "Journalist",
    slug: "journalist",
    description: "Research, investigate, and report on news stories across print, broadcast, and digital media platforms, keeping the public informed about current events.",
    streamTags: ["Arts"],
    salaryMinLKR: 40000,
    salaryMaxLKR: 180000,
    demandLevel: "Low",
    requiredSkills: ["Writing", "Research", "Interviewing", "Communication", "Digital Media"],
    educationPaths: ["BA Mass Communication", "BA Journalism", "Diploma in Media Studies"],
    workEnvironment: "Newsroom / Field",
    imageUrl: "https://images.unsplash.com/photo-1504711434969-e33886168d6c?w=400&h=250&fit=crop",
  },
  {
    title: "Environmental Scientist",
    slug: "environmental-scientist",
    description: "Study environmental problems and develop solutions for issues like pollution, climate change, and natural resource management through field research and data analysis.",
    streamTags: ["Bio", "Maths"],
    salaryMinLKR: 55000,
    salaryMaxLKR: 220000,
    demandLevel: "Medium",
    requiredSkills: ["Environmental Impact Assessment", "GIS", "Data Analysis", "Field Research", "Report Writing"],
    educationPaths: ["BSc Environmental Science", "BSc Geography", "MSc Environmental Management"],
    workEnvironment: "Field / Laboratory / Office",
    imageUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=250&fit=crop",
  },
  {
    title: "Human Resources Manager",
    slug: "human-resources-manager",
    description: "Manage recruitment, employee relations, training, and organisational development. Ensure workplace policies comply with labour laws and support a positive work culture.",
    streamTags: ["Commerce", "Arts"],
    salaryMinLKR: 65000,
    salaryMaxLKR: 300000,
    demandLevel: "Medium",
    requiredSkills: ["Recruitment", "Employee Relations", "Communication", "Labour Law", "Leadership"],
    educationPaths: ["BBA", "BSc HRM", "MBA HR", "CIPM Sri Lanka"],
    workEnvironment: "Office",
    imageUrl: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=400&h=250&fit=crop",
  },
  {
    title: "Quantity Surveyor",
    slug: "quantity-surveyor",
    description: "Manage construction costs from project inception to completion, preparing cost estimates, tender documents, and financial reports for building projects.",
    streamTags: ["Maths", "Commerce"],
    salaryMinLKR: 70000,
    salaryMaxLKR: 320000,
    demandLevel: "Medium",
    requiredSkills: ["Cost Estimation", "Contract Management", "Mathematics", "AutoCAD", "Project Management"],
    educationPaths: ["BSc Quantity Surveying", "NDT QS", "RICS Chartered"],
    workEnvironment: "Office / Construction Site",
    imageUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&h=250&fit=crop",
  },
  {
    title: "DevOps Engineer",
    slug: "devops-engineer",
    description: "Bridge development and operations by automating deployment pipelines, managing cloud infrastructure, and ensuring system reliability and scalability.",
    streamTags: ["Tech", "Maths"],
    salaryMinLKR: 100000,
    salaryMaxLKR: 420000,
    demandLevel: "High",
    requiredSkills: ["Docker", "Kubernetes", "AWS/Azure", "CI/CD", "Linux", "Scripting"],
    educationPaths: ["BSc Computer Science", "BSc IT", "AWS/Azure Certification"],
    workEnvironment: "Office / Remote",
    imageUrl: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=400&h=250&fit=crop",
  },
];

async function seed() {
  const uri = process.env.MONGO_URI;
  if (!uri) { console.error("MONGO_URI not set"); process.exit(1); }

  await mongoose.connect(uri);
  console.log("Connected to MongoDB");

  await Career.deleteMany({});
  console.log("Cleared existing careers");

  const inserted = await Career.insertMany(careers);
  console.log(`Seeded ${inserted.length} careers`);

  await mongoose.disconnect();
  console.log("Done");
}

seed().catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
